namespace DiskGuard.Core.Localization;

/// <summary>
/// 界面词条键。用枚举而不是裸字符串：代码里写错键名会在编译期报错，
/// 各语言词条表缺项也能被 <see cref="Loc.MissingKeys"/> 完整校验。
/// </summary>
public enum LK
{
    // —— 通用 ——
    AppTitle,
    BtnCopy,
    VersionShortFormat,
    VersionFullFormat,
    PrivilegeAdmin,
    PrivilegeUser,
    BtnRestartElevated,
    BtnOpenConfigDir,
    BtnOpenLogDir,

    // —— 顶部状态卡 ——
    LabelMonitorDisk,
    LabelDiskBusy,
    DetailFormat,
    BtnPauseMonitor,
    BtnResumeMonitor,
    BtnReleaseNow,
    TargetNone,
    TargetThrottledFormat,
    ThrottleLevelSuspend,
    ThrottleLevelCapFormat,
    ThrottleLevelCapIopsFormat,
    ThrottleLevelPriority,
    StateMonitoring,
    StatePaused,
    StateWatching,
    StateThrottledFormat,
    StateLevelSuspend,
    StateLevelCap,
    StateLevelPriority,
    StateShareSuffixFormat,

    // —— 标签页 ——
    TabProcess,
    TabSettings,
    TabLog,
    TabAbout,

    // —— 进程与日志列表 ——
    HintProcessList,
    ColProcess,
    ColPid,
    ColOccupancy,
    ColTotal,
    ColRead,
    ColWrite,
    ColStatus,
    ColLogTime,
    ColLogLevel,
    ColLogMessage,
    BtnThrottleSelected,
    BtnReleaseCurrent,
    BtnAddWhitelist,
    BtnRemoveWhitelist,
    BtnClearLog,
    TagThrottledSuspend,
    TagThrottledCap,
    TagThrottledPriority,
    TagSystemKernel,
    TagSystemCritical,
    TagWhitelist,
    TagForeground,

    // —— 设置页 ——
    CardInterface,
    HintInterface,
    LabelLanguage,
    CardTrigger,
    HintTrigger,
    LabelTriggerPercent,
    LabelTriggerSeconds,
    LabelRecoverPercent,
    LabelRecoverSeconds,
    LabelTriggerOccupancy,
    HintTriggerOccupancy,
    LabelTargetOccupancy,
    HintTargetOccupancy,
    LabelMinIops,
    HintMinIops,
    LabelEmergency,
    HintEmergency,
    CardThrottle,
    LabelLowerIoPriority,
    LabelLevel,
    OptionVeryLow,
    OptionLow,
    LabelLowerCpuPriority,
    LabelEnableRateCap,
    LabelCapValue,
    LabelEscalate,
    HintEscalate,
    LabelSuspendMode,
    LabelSuspendRun,
    LabelSuspendPause,
    HintSuspendWarning,
    CardProtection,
    LabelProtectForeground,
    HintProtectForeground,
    LabelWhitelist,
    CardBehavior,
    LabelAutoStart,
    HintAutoStart,
    LabelStartMinimized,
    LabelWriteLog,
    LabelShowBalloon,
    BtnSaveSettings,
    BtnResetSettings,

    // —— 首次启动语言选择 ——
    FirstRunTitle,
    FirstRunPrompt,
    FirstRunDetectedFormat,
    BtnConfirm,
    BtnLater,

    // —— 关于页 ——
    AboutTitle,
    AboutByAuthor,
    AboutSummaryLine1,
    AboutSummaryLine2,
    CardAuthor,
    LabelAuthor,
    AuthorName,
    LabelDouyin,
    LabelXiaohongshu,
    LabelDouyinId,
    LabelXiaohongshuId,
    HintContactAuthor,
    CardOpenSource,
    OpenSourceText,
    BtnOpenProjectHome,
    ThirdPartyText,
    CardDisclaimer,
    DisclaimerText1,
    DisclaimerText2,

    // —— 弹窗与托盘 ——
    MsgSingleInstance,
    MsgUnhandledFormat,
    MsgSelectProcessFirst,
    MsgCannotThrottleFormat,
    MsgSettingsSaved,
    MsgAutoStartNeedsAdmin,
    MsgOpenDirFailedFormat,
    MsgOpenProjectFailedFormat,
    MsgRestartElevatedFailedFormat,
    TrayShowWindow,
    TrayPauseMonitor,
    TrayResumeMonitor,
    TrayReleaseAll,
    TrayExit,
    BalloonStartedTitle,
    BalloonStartedBody,
    BalloonHiddenTitle,
    BalloonHiddenBody,

    // —— 应用日志 ——
    CopyOkFormat,
    CopyFailedFormat,
    LogSettingsSaved,
    LogDefaultsRestored,
    LogWhitelistAddedFormat,
    LogWhitelistRemovedFormat,
    LogLanguageChangedFormat,
    LogTrayReady,
    LogTrayCreateFailed,
    LogTrayInitFailedFormat,
    LogTrayMessageFailedFormat,
    LogTrayUnavailableExit,
    LogUiRefreshFailedFormat,
    LogLogFileWriteFailedFormat,
    LogAutoStartCreated,
    LogAutoStartCreateFailedFormat,
    LogAutoStartNeedAdmin,
    LogAutoStartHandleFailedFormat,
    LogLevelInfo,
    LogLevelWarn,
    LogLevelError,
    ReasonManualRelease,
    ReasonTrayReleaseAll,
    ReasonExit,

    // —— 开机自启服务 ——
    AutoStartEnabled,
    AutoStartEnableFailedFormat,
    AutoStartDisabled,
    AutoStartDisableFailedFormat,
    AutoStartCannotLaunch,
    AutoStartTimeout,

    // —— 内核引擎 ——
    IoModeStarting,
    IoModeEtwFormat,
    IoModeCounters,
    MetricDiskTime,
    MetricBytesApprox,
    EngineMonitorStarted,
    EngineMonitorSwitchedFormat,
    EngineStartFailedFormat,
    EngineRebuildFailedFormat,
    EngineApproxFallback,
    EngineApproxSwitchFailedFormat,
    EngineEtwStalledFormat,
    EngineMonitorPaused,
    EngineMonitorResumed,
    EngineManualThrottleFailedFormat,
    ErrorPermissionOrProtected,
    EngineManualPriorityDoneFormat,
    EngineManualCapDoneFormat,
    EngineCapApplyFailedFormat,
    EngineRestoredFormat,
    EngineRestoredStaleFormat,
    EngineSampleFailedFormat,
    EngineEtwInterruptedFormat,
    DiskLabelFormat,
    DiskLabelWithDrivesFormat,
    DiskAllDisks,
    EngineDiagnosticFormat,
    EngineDiagnosticExtraFormat,
    EngineTargetExitedFormat,
    EngineReasonForeground,
    EngineReasonWhitelisted,
    EngineReasonNoThroughput,
    EngineReasonSwitchHeavier,
    EngineReasonSwitchDisk,
    EngineReasonManualSwitch,
    EngineReasonStopped,
    EngineEmergencyThrottleFormat,
    EngineEmergencyForegroundFormat,
    EngineBusyNoCandidateFormat,
    EngineBusyNoThroughputFormat,
    EngineDefragRunningFormat,
    EngineIdleReleaseFormat,
    EngineHeavierTargetFormat,
    EngineTargetSatisfiedFormat,
    EngineCapDisabledHintFormat,
    EngineCapAppliedFormat,
    EngineCapUnsupportedFormat,
    EngineCapTightenedFormat,
    EngineSuspendEnabledFormat,
    EngineCapAtMinimumFormat,
    EngineThrottleFailedFormat,
    EngineAutoThrottleFormat,
    EngineEmergencyCapFormat,
    EngineIopsCapSuffixFormat,
    EngineForegroundHoldFormat,
    EngineDiskInstanceSuffixFormat,
    IoSourceCleanupStaleFormat,
    IoSourceCleanupFailedFormat,
    IoSourceEtwPrivateOkFormat,
    IoSourceEtwPrivateFailedFormat,
    IoSourceEtwPrivateErrorFormat,
    IoSourceEtwSystemOkFormat,
    IoSourceEtwSystemFailedFormat,
    IoSourceEtwSystemErrorFormat,
    IoSourceEtwUnavailable,
    IoSourceNotElevated,
    IoLevelVeryLow,
    IoLevelLow,
    IoLevelNormal,
    IoLevelHigh,
    IoLevelUnknown
}
